### ISSUE TITLE
Core Dump

### ISSUE THREAD

**Issue by JBAhire** [rajibahmed/adventure#1]
After running in a terminal it's showing core dump i.e segmentation fault. I checked some files but couldn't guess the reason. can you please look into the issue.

**Comment by rajibahmed** [comment]
The system I used to develop in was a debian system 8 years ago. I am sorry I don't have time to fix :(

**Comment by JBAhire** [comment]
Ohh that's fine! I will try to develop my own☺️. Thanks!
